///Supported event types
enum BetterPlayerEventType {
  PLAY,
  PAUSE,
  SEEK_TO,
  OPEN_FULLSCREEN,
  HIDE_FULLSCREEN,
  SET_VOLUME,
  PROGRESS,
  FINISHED,
  EXCEPTION,
  CONTROLS_VISIBLE,
  CONTROLS_HIDDEN,
  SET_SPEED,
  CHANGED_SUBTITLES
}
