include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    flutter_style_todos: false
    avoid_final_parameters: false
    sort_pub_dependencies: false
analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart]