name: better_player_internal_example
resolution: workspace
description: "Example to showcase use cases of Better Player."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: "^3.12.0"
  flutter: ">=3.47.0"

dependencies:
  better_player:
    path: ../
  flutter:
    sdk: flutter

  path_provider: any
dev_dependencies:
  very_good_analysis: ^10.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
