include: package:very_good_analysis/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-dynamic: false

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_catches_without_on_clauses: false
    use_setters_to_change_properties: false
    use_if_null_to_convert_nulls_to_bools: false
    document_ignores: false
    one_member_abstracts: false
    missing_whitespace_between_adjacent_strings: false
    close_sinks: true
    sort_constructors_first: false
    avoid_classes_with_only_static_members: false
    avoid_void_async: false
    avoid_positional_boolean_parameters: false
    avoid_function_literals_in_foreach_calls: false
    prefer_constructors_over_static_methods: false
    sort_unnamed_constructors_first: false
    sized_box_for_whitespace: false
    invalid_dependency: false
    sort_pub_dependencies: false
    avoid_unnecessary_containers: false

