name: better_player_workspace
environment:
  sdk: "^3.13.0"
workspace:
  - packages/better_player
  - packages/better_player_android
  - packages/better_player_ios
  - packages/better_player_platform_interface
  - packages/better_player_example
