name: better_player_android
resolution: workspace
description: The Android implementation of the better_player plugin, offering advanced video playback features using ExoPlayer and JNI for optimized performance in Flutter applications.
version: 1.2.0
homepage: https://github.com/jhomlala/betterplayer/tree/master/packages/better_player_android

environment:
  sdk: "^3.12.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  better_player_platform_interface: ^1.2.0
  jni: ^1.0.3
  jni_flutter: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  jnigen: ^0.17.0
  mocktail: ^1.0.5
  very_good_analysis: ^10.3.0

flutter:
  plugin:
    implements: better_player
    platforms:
      android:
        package: pl.hasoft.better_player
        pluginClass: BetterPlayerPlugin
        dartPluginClass: BetterPlayerAndroid
