// AUTO GENERATED BY JNIGEN 0.17.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `pl.hasoft.better_player.BetterPlayerApi$Companion`
extension type BetterPlayerApi$Companion._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'pl/hasoft/better_player/BetterPlayerApi$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<BetterPlayerApi$Companion> type =
      $BetterPlayerApi$Companion$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory BetterPlayerApi$Companion(
    DefaultConstructorMarker? defaultConstructorMarker,
  ) {
    final _$$classRef = _class.reference;
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$defaultConstructorMarker.pointer,
    ).object<BetterPlayerApi$Companion>();
  }
}

extension BetterPlayerApi$Companion$$Methods on BetterPlayerApi$Companion {
  static final _id_get$textureRegistry = BetterPlayerApi$Companion._class
      .instanceMethodId(
        r'getTextureRegistry',
        r'()Lio/flutter/view/TextureRegistry;',
      );

  static final _get$textureRegistry =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final io.flutter.view.TextureRegistry getTextureRegistry()`
  /// The returned object must be released after use, by calling the [release] method.
  TextureRegistry? get textureRegistry {
    final _$$selfRef = reference;
    return _get$textureRegistry(
      _$$selfRef.pointer,
      _id_get$textureRegistry.pointer,
    ).object<TextureRegistry?>();
  }

  static final _id_set$textureRegistry = BetterPlayerApi$Companion._class
      .instanceMethodId(
        r'setTextureRegistry',
        r'(Lio/flutter/view/TextureRegistry;)V',
      );

  static final _set$textureRegistry =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final void setTextureRegistry(io.flutter.view.TextureRegistry textureRegistry)`
  set textureRegistry(TextureRegistry? textureRegistry) {
    final _$$selfRef = reference;
    final _$textureRegistry =
        textureRegistry?.reference ?? jni$_.jNullReference;
    _set$textureRegistry(
      _$$selfRef.pointer,
      _id_set$textureRegistry.pointer,
      _$textureRegistry.pointer,
    ).check();
  }

  static final _id_createPlayer = BetterPlayerApi$Companion._class.instanceMethodId(
    r'createPlayer',
    r'(Landroid/content/Context;Lpl/hasoft/better_player/BetterPlayerCallback;)Lpl/hasoft/better_player/BetterPlayer;',
  );

  static final _createPlayer =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun createPlayer(context: android.content.Context, callback: pl.hasoft.better_player.BetterPlayerCallback): pl.hasoft.better_player.BetterPlayer?`
  /// The returned object must be released after use, by calling the [release] method.
  BetterPlayer? createPlayer(
    Context context,
    BetterPlayerCallback betterPlayerCallback,
  ) {
    final _$$selfRef = reference;
    final _$context = context.reference;
    final _$betterPlayerCallback = betterPlayerCallback.reference;
    return _createPlayer(
      _$$selfRef.pointer,
      _id_createPlayer.pointer,
      _$context.pointer,
      _$betterPlayerCallback.pointer,
    ).object<BetterPlayer?>();
  }
}

final class $BetterPlayerApi$Companion$Type$
    extends jni$_.JType<BetterPlayerApi$Companion> {
  @jni$_.internal
  const $BetterPlayerApi$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lpl/hasoft/better_player/BetterPlayerApi$Companion;';
}

/// from: `pl.hasoft.better_player.BetterPlayerApi`
extension type BetterPlayerApi._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'pl/hasoft/better_player/BetterPlayerApi',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<BetterPlayerApi> type = $BetterPlayerApi$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Lpl/hasoft/better_player/BetterPlayerApi$Companion;',
  );

  /// from: `static public final pl.hasoft.better_player.BetterPlayerApi$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static BetterPlayerApi$Companion get Companion =>
      _id_Companion.get(_class, BetterPlayerApi$Companion.type)
          as BetterPlayerApi$Companion;

  static final _id_new$ = _class.constructorId(
    r'()V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory BetterPlayerApi() {
    final _$$classRef = _class.reference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
    ).object<BetterPlayerApi>();
  }
}

final class $BetterPlayerApi$Type$ extends jni$_.JType<BetterPlayerApi> {
  @jni$_.internal
  const $BetterPlayerApi$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lpl/hasoft/better_player/BetterPlayerApi;';
}

/// from: `pl.hasoft.better_player.BetterPlayerCallback`
extension type BetterPlayerCallback._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'pl/hasoft/better_player/BetterPlayerCallback',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<BetterPlayerCallback> type =
      $BetterPlayerCallback$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<core$_.int, $BetterPlayerCallback> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(
        0,
        descriptor.address,
        args.address,
      ),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onEvent(Ljava/lang/String;Ljava/util/Map;)V') {
        _$impls[$p]!.onEvent(
          ($a![0] as jni$_.JString),
          ($a![1] as jni$_.JMap<jni$_.JString, jni$_.JObject?>),
        );
        return jni$_.nullptr;
      }
      if ($d ==
          r'onError(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V') {
        _$impls[$p]!.onError(
          ($a![0] as jni$_.JString),
          ($a![1] as jni$_.JString),
          ($a![2] as jni$_.JString),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $BetterPlayerCallback $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      $i.args?.release();
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'pl.hasoft.better_player.BetterPlayerCallback',
      $p,
      _$invokePointer,
      [
        if ($impl.onEvent$async) r'onEvent(Ljava/lang/String;Ljava/util/Map;)V',
        if ($impl.onError$async)
          r'onError(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory BetterPlayerCallback.implement(
    $BetterPlayerCallback $impl,
  ) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<BetterPlayerCallback>();
  }
}

extension BetterPlayerCallback$$Methods on BetterPlayerCallback {
  static final _id_onEvent = BetterPlayerCallback._class.instanceMethodId(
    r'onEvent',
    r'(Ljava/lang/String;Ljava/util/Map;)V',
  );

  static final _onEvent =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onEvent(event: kotlin.String, parameters: kotlin.collections.Map<kotlin.String, kotlin.Any?>): kotlin.Unit`
  void onEvent(
    jni$_.JString string,
    jni$_.JMap<jni$_.JString, jni$_.JObject?> map,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$map = map.reference;
    _onEvent(
      _$$selfRef.pointer,
      _id_onEvent.pointer,
      _$string.pointer,
      _$map.pointer,
    ).check();
  }

  static final _id_onError = BetterPlayerCallback._class.instanceMethodId(
    r'onError',
    r'(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _onError =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun onError(errorCode: kotlin.String, errorMessage: kotlin.String, errorDetails: kotlin.String): kotlin.Unit`
  void onError(
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    _onError(
      _$$selfRef.pointer,
      _id_onError.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
    ).check();
  }
}

abstract base mixin class $BetterPlayerCallback {
  factory $BetterPlayerCallback({
    required void Function(
      jni$_.JString string,
      jni$_.JMap<jni$_.JString, jni$_.JObject?> map,
    )
    onEvent,
    core$_.bool onEvent$async,
    required void Function(
      jni$_.JString string,
      jni$_.JString string1,
      jni$_.JString string2,
    )
    onError,
    core$_.bool onError$async,
  }) = _$BetterPlayerCallback;

  void onEvent(
    jni$_.JString string,
    jni$_.JMap<jni$_.JString, jni$_.JObject?> map,
  );
  core$_.bool get onEvent$async => false;
  void onError(
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
  );
  core$_.bool get onError$async => false;
}

final class _$BetterPlayerCallback with $BetterPlayerCallback {
  _$BetterPlayerCallback({
    required void Function(
      jni$_.JString string,
      jni$_.JMap<jni$_.JString, jni$_.JObject?> map,
    )
    onEvent,
    this.onEvent$async = false,
    required void Function(
      jni$_.JString string,
      jni$_.JString string1,
      jni$_.JString string2,
    )
    onError,
    this.onError$async = false,
  }) : _onEvent = onEvent,
       _onError = onError;

  final void Function(
    jni$_.JString string,
    jni$_.JMap<jni$_.JString, jni$_.JObject?> map,
  )
  _onEvent;
  final core$_.bool onEvent$async;
  final void Function(
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
  )
  _onError;
  final core$_.bool onError$async;

  void onEvent(
    jni$_.JString string,
    jni$_.JMap<jni$_.JString, jni$_.JObject?> map,
  ) {
    return _onEvent(string, map);
  }

  void onError(
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
  ) {
    return _onError(string, string1, string2);
  }
}

final class $BetterPlayerCallback$Type$
    extends jni$_.JType<BetterPlayerCallback> {
  @jni$_.internal
  const $BetterPlayerCallback$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lpl/hasoft/better_player/BetterPlayerCallback;';
}

/// from: `pl.hasoft.better_player.BetterPlayer$Companion`
extension type BetterPlayer$Companion._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'pl/hasoft/better_player/BetterPlayer$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<BetterPlayer$Companion> type =
      $BetterPlayer$Companion$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory BetterPlayer$Companion(
    DefaultConstructorMarker? defaultConstructorMarker,
  ) {
    final _$$classRef = _class.reference;
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$defaultConstructorMarker.pointer,
    ).object<BetterPlayer$Companion>();
  }
}

extension BetterPlayer$Companion$$Methods on BetterPlayer$Companion {
  static final _id_clearCache = BetterPlayer$Companion._class.instanceMethodId(
    r'clearCache',
    r'(Landroid/content/Context;)V',
  );

  static final _clearCache =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun clearCache(context: android.content.Context?): kotlin.Unit`
  void clearCache(
    Context? context,
  ) {
    final _$$selfRef = reference;
    final _$context = context?.reference ?? jni$_.jNullReference;
    _clearCache(
      _$$selfRef.pointer,
      _id_clearCache.pointer,
      _$context.pointer,
    ).check();
  }

  static final _id_preCache = BetterPlayer$Companion._class.instanceMethodId(
    r'preCache',
    r'(Landroid/content/Context;Ljava/lang/String;JJJLjava/util/Map;Ljava/lang/String;)V',
  );

  static final _preCache =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int64,
                    jni$_.Int64,
                    jni$_.Int64,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun preCache(context: android.content.Context?, dataSource: kotlin.String?, preCacheSize: kotlin.Long, maxCacheSize: kotlin.Long, maxCacheFileSize: kotlin.Long, headers: kotlin.collections.Map<kotlin.String, kotlin.String?>, cacheKey: kotlin.String?): kotlin.Unit`
  void preCache(
    Context? context,
    jni$_.JString? string,
    core$_.int j,
    core$_.int j1,
    core$_.int j2,
    jni$_.JMap<jni$_.JString, jni$_.JString?> map,
    jni$_.JString? string1,
  ) {
    final _$$selfRef = reference;
    final _$context = context?.reference ?? jni$_.jNullReference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$map = map.reference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    _preCache(
      _$$selfRef.pointer,
      _id_preCache.pointer,
      _$context.pointer,
      _$string.pointer,
      j,
      j1,
      j2,
      _$map.pointer,
      _$string1.pointer,
    ).check();
  }

  static final _id_stopPreCache = BetterPlayer$Companion._class
      .instanceMethodId(
        r'stopPreCache',
        r'(Landroid/content/Context;Ljava/lang/String;)V',
      );

  static final _stopPreCache =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun stopPreCache(context: android.content.Context?, url: kotlin.String?): kotlin.Unit`
  void stopPreCache(
    Context? context,
    jni$_.JString? string,
  ) {
    final _$$selfRef = reference;
    final _$context = context?.reference ?? jni$_.jNullReference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    _stopPreCache(
      _$$selfRef.pointer,
      _id_stopPreCache.pointer,
      _$context.pointer,
      _$string.pointer,
    ).check();
  }
}

final class $BetterPlayer$Companion$Type$
    extends jni$_.JType<BetterPlayer$Companion> {
  @jni$_.internal
  const $BetterPlayer$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lpl/hasoft/better_player/BetterPlayer$Companion;';
}

/// from: `pl.hasoft.better_player.BetterPlayer`
extension type BetterPlayer._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'pl/hasoft/better_player/BetterPlayer',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<BetterPlayer> type = $BetterPlayer$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Lpl/hasoft/better_player/BetterPlayer$Companion;',
  );

  /// from: `static public final pl.hasoft.better_player.BetterPlayer$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static BetterPlayer$Companion get Companion =>
      _id_Companion.get(_class, BetterPlayer$Companion.type)
          as BetterPlayer$Companion;

  static final _id_new$ = _class.constructorId(
    r'(Landroid/content/Context;Lio/flutter/view/TextureRegistry$SurfaceTextureEntry;Lpl/hasoft/better_player/BetterPlayerCallback;Lpl/hasoft/better_player/CustomDefaultLoadControl;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.content.Context context, io.flutter.view.TextureRegistry$SurfaceTextureEntry surfaceTextureEntry, pl.hasoft.better_player.BetterPlayerCallback betterPlayerCallback, pl.hasoft.better_player.CustomDefaultLoadControl customDefaultLoadControl)`
  /// The returned object must be released after use, by calling the [release] method.
  factory BetterPlayer(
    Context context,
    TextureRegistry$$SurfaceTextureEntry surfaceTextureEntry,
    BetterPlayerCallback betterPlayerCallback,
    CustomDefaultLoadControl? customDefaultLoadControl,
  ) {
    final _$$classRef = _class.reference;
    final _$context = context.reference;
    final _$surfaceTextureEntry = surfaceTextureEntry.reference;
    final _$betterPlayerCallback = betterPlayerCallback.reference;
    final _$customDefaultLoadControl =
        customDefaultLoadControl?.reference ?? jni$_.jNullReference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$context.pointer,
      _$surfaceTextureEntry.pointer,
      _$betterPlayerCallback.pointer,
      _$customDefaultLoadControl.pointer,
    ).object<BetterPlayer>();
  }

  static final _id_new$1 = _class.constructorId(
    r'(Landroid/content/Context;Lio/flutter/view/TextureRegistry$SurfaceTextureEntry;Lpl/hasoft/better_player/BetterPlayerCallback;Lpl/hasoft/better_player/CustomDefaultLoadControl;ILkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(android.content.Context context, io.flutter.view.TextureRegistry$SurfaceTextureEntry surfaceTextureEntry, pl.hasoft.better_player.BetterPlayerCallback betterPlayerCallback, pl.hasoft.better_player.CustomDefaultLoadControl customDefaultLoadControl, int i, kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory BetterPlayer.new$1(
    Context? context,
    TextureRegistry$$SurfaceTextureEntry? surfaceTextureEntry,
    BetterPlayerCallback? betterPlayerCallback,
    CustomDefaultLoadControl? customDefaultLoadControl,
    core$_.int i,
    DefaultConstructorMarker? defaultConstructorMarker,
  ) {
    final _$$classRef = _class.reference;
    final _$context = context?.reference ?? jni$_.jNullReference;
    final _$surfaceTextureEntry =
        surfaceTextureEntry?.reference ?? jni$_.jNullReference;
    final _$betterPlayerCallback =
        betterPlayerCallback?.reference ?? jni$_.jNullReference;
    final _$customDefaultLoadControl =
        customDefaultLoadControl?.reference ?? jni$_.jNullReference;
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return _new$1(
      _$$classRef.pointer,
      _id_new$1.pointer,
      _$context.pointer,
      _$surfaceTextureEntry.pointer,
      _$betterPlayerCallback.pointer,
      _$customDefaultLoadControl.pointer,
      i,
      _$defaultConstructorMarker.pointer,
    ).object<BetterPlayer>();
  }
}

extension BetterPlayer$$Methods on BetterPlayer {
  static final _id_setDataSource = BetterPlayer._class.instanceMethodId(
    r'setDataSource',
    r'(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/Map;ZJJJLjava/lang/String;Ljava/util/Map;Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _setDataSource =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Int64,
                    jni$_.Int64,
                    jni$_.Int64,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
              core$_.int,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun setDataSource(context: android.content.Context, key: kotlin.String?, dataSource: kotlin.String?, formatHint: kotlin.String?, headers: kotlin.collections.Map<kotlin.String, kotlin.String>?, useCache: kotlin.Boolean, maxCacheSize: kotlin.Long, maxCacheFileSize: kotlin.Long, overriddenDuration: kotlin.Long, licenseUrl: kotlin.String?, drmHeaders: kotlin.collections.Map<kotlin.String, kotlin.String>?, cacheKey: kotlin.String?, clearKey: kotlin.String?): kotlin.Unit`
  void setDataSource(
    Context context,
    jni$_.JString? string,
    jni$_.JString? string1,
    jni$_.JString? string2,
    jni$_.JMap<jni$_.JString, jni$_.JString>? map,
    core$_.bool z,
    core$_.int j,
    core$_.int j1,
    core$_.int j2,
    jni$_.JString? string3,
    jni$_.JMap<jni$_.JString, jni$_.JString>? map1,
    jni$_.JString? string4,
    jni$_.JString? string5,
  ) {
    final _$$selfRef = reference;
    final _$context = context.reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2?.reference ?? jni$_.jNullReference;
    final _$map = map?.reference ?? jni$_.jNullReference;
    final _$string3 = string3?.reference ?? jni$_.jNullReference;
    final _$map1 = map1?.reference ?? jni$_.jNullReference;
    final _$string4 = string4?.reference ?? jni$_.jNullReference;
    final _$string5 = string5?.reference ?? jni$_.jNullReference;
    _setDataSource(
      _$$selfRef.pointer,
      _id_setDataSource.pointer,
      _$context.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
      _$map.pointer,
      z ? 1 : 0,
      j,
      j1,
      j2,
      _$string3.pointer,
      _$map1.pointer,
      _$string4.pointer,
      _$string5.pointer,
    ).check();
  }

  static final _id_setupPlayerNotification = BetterPlayer._class.instanceMethodId(
    r'setupPlayerNotification',
    r'(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _setupPlayerNotification =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun setupPlayerNotification(context: android.content.Context, title: kotlin.String, author: kotlin.String?, imageUrl: kotlin.String?, notificationChannelName: kotlin.String?, activityName: kotlin.String): kotlin.Unit`
  void setupPlayerNotification(
    Context context,
    jni$_.JString string,
    jni$_.JString? string1,
    jni$_.JString? string2,
    jni$_.JString? string3,
    jni$_.JString string4,
  ) {
    final _$$selfRef = reference;
    final _$context = context.reference;
    final _$string = string.reference;
    final _$string1 = string1?.reference ?? jni$_.jNullReference;
    final _$string2 = string2?.reference ?? jni$_.jNullReference;
    final _$string3 = string3?.reference ?? jni$_.jNullReference;
    final _$string4 = string4.reference;
    _setupPlayerNotification(
      _$$selfRef.pointer,
      _id_setupPlayerNotification.pointer,
      _$context.pointer,
      _$string.pointer,
      _$string1.pointer,
      _$string2.pointer,
      _$string3.pointer,
      _$string4.pointer,
    ).check();
  }

  static final _id_disposeRemoteNotifications = BetterPlayer._class
      .instanceMethodId(
        r'disposeRemoteNotifications',
        r'()V',
      );

  static final _disposeRemoteNotifications =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun disposeRemoteNotifications(): kotlin.Unit`
  void disposeRemoteNotifications() {
    final _$$selfRef = reference;
    _disposeRemoteNotifications(
      _$$selfRef.pointer,
      _id_disposeRemoteNotifications.pointer,
    ).check();
  }

  static final _id_sendBufferingUpdate = BetterPlayer._class.instanceMethodId(
    r'sendBufferingUpdate',
    r'(Z)V',
  );

  static final _sendBufferingUpdate =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public fun sendBufferingUpdate(isFromBufferingStart: kotlin.Boolean): kotlin.Unit`
  void sendBufferingUpdate(
    core$_.bool z,
  ) {
    final _$$selfRef = reference;
    _sendBufferingUpdate(
      _$$selfRef.pointer,
      _id_sendBufferingUpdate.pointer,
      z ? 1 : 0,
    ).check();
  }

  static final _id_play = BetterPlayer._class.instanceMethodId(
    r'play',
    r'()V',
  );

  static final _play =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun play(): kotlin.Unit`
  void play() {
    final _$$selfRef = reference;
    _play(_$$selfRef.pointer, _id_play.pointer).check();
  }

  static final _id_pause = BetterPlayer._class.instanceMethodId(
    r'pause',
    r'()V',
  );

  static final _pause =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun pause(): kotlin.Unit`
  void pause() {
    final _$$selfRef = reference;
    _pause(_$$selfRef.pointer, _id_pause.pointer).check();
  }

  static final _id_set$looping = BetterPlayer._class.instanceMethodId(
    r'setLooping',
    r'(Z)V',
  );

  static final _set$looping =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public fun setLooping(value: kotlin.Boolean): kotlin.Unit`
  set looping(core$_.bool z) {
    final _$$selfRef = reference;
    _set$looping(
      _$$selfRef.pointer,
      _id_set$looping.pointer,
      z ? 1 : 0,
    ).check();
  }

  static final _id_set$volume = BetterPlayer._class.instanceMethodId(
    r'setVolume',
    r'(D)V',
  );

  static final _set$volume =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Double,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.double,
            )
          >();

  /// from: `public fun setVolume(value: kotlin.Double): kotlin.Unit`
  set volume(core$_.double d) {
    final _$$selfRef = reference;
    _set$volume(_$$selfRef.pointer, _id_set$volume.pointer, d).check();
  }

  static final _id_set$speed = BetterPlayer._class.instanceMethodId(
    r'setSpeed',
    r'(D)V',
  );

  static final _set$speed =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Double,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.double,
            )
          >();

  /// from: `public fun setSpeed(value: kotlin.Double): kotlin.Unit`
  set speed(core$_.double d) {
    final _$$selfRef = reference;
    _set$speed(_$$selfRef.pointer, _id_set$speed.pointer, d).check();
  }

  static final _id_setTrackParameters = BetterPlayer._class.instanceMethodId(
    r'setTrackParameters',
    r'(III)V',
  );

  static final _setTrackParameters =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public fun setTrackParameters(width: kotlin.Int, height: kotlin.Int, bitrate: kotlin.Int): kotlin.Unit`
  void setTrackParameters(
    core$_.int i,
    core$_.int i1,
    core$_.int i2,
  ) {
    final _$$selfRef = reference;
    _setTrackParameters(
      _$$selfRef.pointer,
      _id_setTrackParameters.pointer,
      i,
      i1,
      i2,
    ).check();
  }

  static final _id_seekTo = BetterPlayer._class.instanceMethodId(
    r'seekTo',
    r'(I)V',
  );

  static final _seekTo =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public fun seekTo(location: kotlin.Int): kotlin.Unit`
  void seekTo(
    core$_.int i,
  ) {
    final _$$selfRef = reference;
    _seekTo(_$$selfRef.pointer, _id_seekTo.pointer, i).check();
  }

  static final _id_get$position = BetterPlayer._class.instanceMethodId(
    r'getPosition',
    r'()J',
  );

  static final _get$position =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final long getPosition()`
  core$_.int get position {
    final _$$selfRef = reference;
    return _get$position(_$$selfRef.pointer, _id_get$position.pointer).long;
  }

  static final _id_get$absolutePosition = BetterPlayer._class.instanceMethodId(
    r'getAbsolutePosition',
    r'()J',
  );

  static final _get$absolutePosition =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallLongMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final long getAbsolutePosition()`
  core$_.int get absolutePosition {
    final _$$selfRef = reference;
    return _get$absolutePosition(
      _$$selfRef.pointer,
      _id_get$absolutePosition.pointer,
    ).long;
  }

  static final _id_setupMediaSession = BetterPlayer._class.instanceMethodId(
    r'setupMediaSession',
    r'(Landroid/content/Context;)Landroidx/media3/session/MediaSession;',
  );

  static final _setupMediaSession =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun setupMediaSession(context: android.content.Context?): androidx.media3.session.MediaSession?`
  /// The returned object must be released after use, by calling the [release] method.
  MediaSession? setupMediaSession(
    Context? context,
  ) {
    final _$$selfRef = reference;
    final _$context = context?.reference ?? jni$_.jNullReference;
    return _setupMediaSession(
      _$$selfRef.pointer,
      _id_setupMediaSession.pointer,
      _$context.pointer,
    ).object<MediaSession?>();
  }

  static final _id_onPictureInPictureStatusChanged = BetterPlayer._class
      .instanceMethodId(
        r'onPictureInPictureStatusChanged',
        r'(Z)V',
      );

  static final _onPictureInPictureStatusChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public fun onPictureInPictureStatusChanged(inPip: kotlin.Boolean): kotlin.Unit`
  void onPictureInPictureStatusChanged(
    core$_.bool z,
  ) {
    final _$$selfRef = reference;
    _onPictureInPictureStatusChanged(
      _$$selfRef.pointer,
      _id_onPictureInPictureStatusChanged.pointer,
      z ? 1 : 0,
    ).check();
  }

  static final _id_disposeMediaSession = BetterPlayer._class.instanceMethodId(
    r'disposeMediaSession',
    r'()V',
  );

  static final _disposeMediaSession =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun disposeMediaSession(): kotlin.Unit`
  void disposeMediaSession() {
    final _$$selfRef = reference;
    _disposeMediaSession(
      _$$selfRef.pointer,
      _id_disposeMediaSession.pointer,
    ).check();
  }

  static final _id_setAudioTrack = BetterPlayer._class.instanceMethodId(
    r'setAudioTrack',
    r'(Ljava/lang/String;I)V',
  );

  static final _setAudioTrack =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
            )
          >();

  /// from: `public fun setAudioTrack(name: kotlin.String, index: kotlin.Int): kotlin.Unit`
  void setAudioTrack(
    jni$_.JString string,
    core$_.int i,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    _setAudioTrack(
      _$$selfRef.pointer,
      _id_setAudioTrack.pointer,
      _$string.pointer,
      i,
    ).check();
  }

  static final _id_set$mixWithOthers = BetterPlayer._class.instanceMethodId(
    r'setMixWithOthers',
    r'(Z)V',
  );

  static final _set$mixWithOthers =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public fun setMixWithOthers(mixWithOthers: kotlin.Boolean): kotlin.Unit`
  set mixWithOthers(core$_.bool z) {
    final _$$selfRef = reference;
    _set$mixWithOthers(
      _$$selfRef.pointer,
      _id_set$mixWithOthers.pointer,
      z ? 1 : 0,
    ).check();
  }

  static final _id_dispose = BetterPlayer._class.instanceMethodId(
    r'dispose',
    r'()V',
  );

  static final _dispose =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun dispose(): kotlin.Unit`
  void dispose() {
    final _$$selfRef = reference;
    _dispose(_$$selfRef.pointer, _id_dispose.pointer).check();
  }

  static final _id_equals = BetterPlayer._class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public operator fun equals(other: kotlin.Any?): kotlin.Boolean`
  core$_.bool equals(
    jni$_.JObject? object,
  ) {
    final _$$selfRef = reference;
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      _$$selfRef.pointer,
      _id_equals.pointer,
      _$object.pointer,
    ).boolean;
  }

  static final _id_hashCode$1 = BetterPlayer._class.instanceMethodId(
    r'hashCode',
    r'()I',
  );

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun hashCode(): kotlin.Int`
  core$_.int hashCode$1() {
    final _$$selfRef = reference;
    return _hashCode$1(_$$selfRef.pointer, _id_hashCode$1.pointer).integer;
  }
}

final class $BetterPlayer$Type$ extends jni$_.JType<BetterPlayer> {
  @jni$_.internal
  const $BetterPlayer$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lpl/hasoft/better_player/BetterPlayer;';
}

/// from: `io.flutter.view.TextureRegistry`
///
/// WARNING: TextureRegistry is a stub. To generate bindings for this class, include
/// io.flutter.view.TextureRegistry in your config's classes list.
///
extension type TextureRegistry._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static const jni$_.JType<TextureRegistry> type = $TextureRegistry$Type$();
}

final class $TextureRegistry$Type$ extends jni$_.JType<TextureRegistry> {
  @jni$_.internal
  const $TextureRegistry$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lio/flutter/view/TextureRegistry;';
}

/// from: `android.content.Context`
///
/// WARNING: Context is a stub. To generate bindings for this class, include
/// android.content.Context in your config's classes list.
///
extension type Context._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Context> type = $Context$Type$();
}

final class $Context$Type$ extends jni$_.JType<Context> {
  @jni$_.internal
  const $Context$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/content/Context;';
}

/// from: `kotlin.jvm.internal.DefaultConstructorMarker`
///
/// WARNING: DefaultConstructorMarker is a stub. To generate bindings for this class, include
/// kotlin.jvm.internal.DefaultConstructorMarker in your config's classes list.
///
extension type DefaultConstructorMarker._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static const jni$_.JType<DefaultConstructorMarker> type =
      $DefaultConstructorMarker$Type$();
}

final class $DefaultConstructorMarker$Type$
    extends jni$_.JType<DefaultConstructorMarker> {
  @jni$_.internal
  const $DefaultConstructorMarker$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lkotlin/jvm/internal/DefaultConstructorMarker;';
}

/// from: `io.flutter.view.TextureRegistry$SurfaceTextureEntry`
///
/// WARNING: TextureRegistry$$SurfaceTextureEntry is a stub. To generate bindings for this class, include
/// io.flutter.view.TextureRegistry$SurfaceTextureEntry in your config's classes list.
///
extension type TextureRegistry$$SurfaceTextureEntry._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static const jni$_.JType<TextureRegistry$$SurfaceTextureEntry> type =
      $TextureRegistry$$SurfaceTextureEntry$Type$();
}

final class $TextureRegistry$$SurfaceTextureEntry$Type$
    extends jni$_.JType<TextureRegistry$$SurfaceTextureEntry> {
  @jni$_.internal
  const $TextureRegistry$$SurfaceTextureEntry$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lio/flutter/view/TextureRegistry$SurfaceTextureEntry;';
}

/// from: `pl.hasoft.better_player.CustomDefaultLoadControl`
///
/// WARNING: CustomDefaultLoadControl is a stub. To generate bindings for this class, include
/// pl.hasoft.better_player.CustomDefaultLoadControl in your config's classes list.
///
extension type CustomDefaultLoadControl._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static const jni$_.JType<CustomDefaultLoadControl> type =
      $CustomDefaultLoadControl$Type$();
}

final class $CustomDefaultLoadControl$Type$
    extends jni$_.JType<CustomDefaultLoadControl> {
  @jni$_.internal
  const $CustomDefaultLoadControl$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lpl/hasoft/better_player/CustomDefaultLoadControl;';
}

/// from: `androidx.media3.session.MediaSession`
///
/// WARNING: MediaSession is a stub. To generate bindings for this class, include
/// androidx.media3.session.MediaSession in your config's classes list.
///
extension type MediaSession._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<MediaSession> type = $MediaSession$Type$();
}

final class $MediaSession$Type$ extends jni$_.JType<MediaSession> {
  @jni$_.internal
  const $MediaSession$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroidx/media3/session/MediaSession;';
}
