name: better_player_ios
resolution: workspace
description: iOS implementation of the better_player plugin.
version: 1.0.2
homepage: https://github.com/jhomlala/betterplayer/tree/master/packages/better_player_ios

environment:
  sdk: "^3.12.0"
  flutter: ">=3.47.0"

dependencies:
  objective_c: ^9.5.0
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  better_player_platform_interface: ^1.0.2

dev_dependencies:
  ffigen: ^21.0.0
  flutter_test:
    sdk: flutter
  swiftgen: ^0.1.3
  very_good_analysis: ^10.3.0

  logging: any
  mocktail: ^1.0.5
flutter:
  plugin:
    implements: better_player
    platforms:
      ios:
        pluginClass: BetterPlayerPlugin
        dartPluginClass: BetterPlayerIOS
