plugins {
    id 'com.android.library'
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21
    }
}

android {
    namespace "com.jhomlala.better_player"
    compileSdkVersion 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 16
    }

    dependencies {
        def media3Version = "1.1.1"
        def lifecycleVersion = "2.4.0-beta01"
        def annotationVersion = "1.2.0"
        def workVersion = "2.7.0"

        implementation "androidx.media3:media3-exoplayer:$media3Version"
        implementation "androidx.media3:media3-datasource:$media3Version"
        implementation "androidx.media3:media3-common:$media3Version"
        implementation "androidx.media3:media3-exoplayer-hls:$media3Version"
        implementation "androidx.media3:media3-exoplayer-dash:$media3Version"
        implementation "androidx.media3:media3-exoplayer-smoothstreaming:$media3Version"
        implementation "androidx.media3:media3-ui:$media3Version"
        implementation "androidx.media3:media3-session:$media3Version"
        implementation "androidx.media:media:1.6.0"
        implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycleVersion"
        implementation "androidx.lifecycle:lifecycle-common:$lifecycleVersion"
        implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycleVersion"
        implementation "androidx.annotation:annotation:$annotationVersion"
        implementation "androidx.work:work-runtime:$workVersion"
    }
}
