group 'com.jhomlala.better_player.better_player'
version '1.0-SNAPSHOT'

buildscript {
    ext.exoPlayerVersion = "2.19.1"
    ext.lifecycleVersion = "2.8.7"
    ext.annotationVersion = "1.2.0"
    ext.workVersion = "2.10.0"
    ext.coreVersion = "1.6.0"
    

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdk 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdk 21
    }

    dependencies {
        implementation "com.google.android.exoplayer:exoplayer-core:$exoPlayerVersion"
        implementation "com.google.android.exoplayer:exoplayer-hls:$exoPlayerVersion"
        implementation "com.google.android.exoplayer:exoplayer-dash:$exoPlayerVersion"
        implementation "com.google.android.exoplayer:exoplayer-smoothstreaming:$exoPlayerVersion"
        implementation "com.google.android.exoplayer:exoplayer-ui:$exoPlayerVersion"
        implementation "com.google.android.exoplayer:extension-mediasession:$exoPlayerVersion"
        implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycleVersion"
        implementation "androidx.lifecycle:lifecycle-common:$lifecycleVersion"
        implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycleVersion"
        implementation "androidx.annotation:annotation:$annotationVersion"
        implementation "androidx.work:work-runtime:$workVersion"
    }

    namespace 'com.jhomlala.better_player.better_player'
}

