name: better_player_platform_interface
resolution: workspace
description: A common platform interface for the better_player plugin.
version: 1.0.0
homepage: https://github.com/jhomlala/betterplayer/tree/master/packages/better_player_platform_interface

environment:
  sdk: "^3.12.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  meta: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
