name: Deploy to home.pl

on:
  push:
    branches:
      - master  # Or main, depending on your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          working-directory: hasoft_website

      - name: Build Jekyll
        run: |
          bundle install
          bundle exec jekyll build
        working-directory: hasoft_website

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: hasoft_website/_site/
          server-dir: /  # Adjust if you want to deploy to a subdirectory
