// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

const _$objcVersionCheck = objc.ObjCVersionCheck(9, 5);
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<objc.ObjCObjectImpl>,
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<objc.ObjCObjectImpl>,
    ffi.Pointer<objc.ObjCObjectImpl>,
    ffi.Pointer<objc.ObjCObjectImpl>,
  )
>()
external void _x224me_protocolTrampoline_1tz5yf(
  ffi.Pointer<objc.ObjCObjectImpl> target,
  ffi.Pointer<ffi.Void> arg0,
  ffi.Pointer<objc.ObjCObjectImpl> arg1,
  ffi.Pointer<objc.ObjCObjectImpl> arg2,
  ffi.Pointer<objc.ObjCObjectImpl> arg3,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<objc.ObjCObjectImpl>,
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<objc.ObjCObjectImpl>,
    ffi.Pointer<objc.ObjCObjectImpl>,
  )
>()
external void _x224me_protocolTrampoline_fjrv01(
  ffi.Pointer<objc.ObjCObjectImpl> target,
  ffi.Pointer<ffi.Void> arg0,
  ffi.Pointer<objc.ObjCObjectImpl> arg1,
  ffi.Pointer<objc.ObjCObjectImpl> arg2,
);

@ffi.Native<
  ffi.Pointer<objc.ObjCBlockImpl> Function(
    ffi.Int64,
    ffi.Pointer<objc.DOBJC_Context>,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl> args)
      >
    >,
  )
>(isLeaf: true)
external ffi.Pointer<objc.ObjCBlockImpl> _x224me_wrapBlockingBlock_1s56lr9(
  int port,
  ffi.Pointer<objc.DOBJC_Context> context,
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl> args)>
  >
  directInvoke,
);

@ffi.Native<
  ffi.Pointer<objc.ObjCBlockImpl> Function(
    ffi.Int64,
    ffi.Pointer<objc.DOBJC_Context>,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl> args)
      >
    >,
  )
>(isLeaf: true)
external ffi.Pointer<objc.ObjCBlockImpl> _x224me_wrapBlockingBlock_1tz5yf(
  int port,
  ffi.Pointer<objc.DOBJC_Context> context,
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl> args)>
  >
  directInvoke,
);

@ffi.Native<
  ffi.Pointer<objc.ObjCBlockImpl> Function(
    ffi.Int64,
    ffi.Pointer<objc.DOBJC_Context>,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl> args)
      >
    >,
  )
>(isLeaf: true)
external ffi.Pointer<objc.ObjCBlockImpl> _x224me_wrapBlockingBlock_fjrv01(
  int port,
  ffi.Pointer<objc.DOBJC_Context> context,
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl> args)>
  >
  directInvoke,
);

@ffi.Native<
  ffi.Pointer<objc.ObjCBlockImpl> Function(
    ffi.Int64,
    ffi.Pointer<objc.DOBJC_Context>,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl> args)
      >
    >,
  )
>(isLeaf: true)
external ffi.Pointer<objc.ObjCBlockImpl> _x224me_wrapBlockingBlock_xtuoz7(
  int port,
  ffi.Pointer<objc.DOBJC_Context> context,
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl> args)>
  >
  directInvoke,
);

@ffi.Native<
  ffi.Pointer<objc.ObjCBlockImpl> Function(
    ffi.Int64,
    ffi.Pointer<objc.DOBJC_Context>,
  )
>(isLeaf: true)
external ffi.Pointer<objc.ObjCBlockImpl> _x224me_wrapListenerBlock_1s56lr9(
  int port,
  ffi.Pointer<objc.DOBJC_Context> context,
);

@ffi.Native<
  ffi.Pointer<objc.ObjCBlockImpl> Function(
    ffi.Int64,
    ffi.Pointer<objc.DOBJC_Context>,
  )
>(isLeaf: true)
external ffi.Pointer<objc.ObjCBlockImpl> _x224me_wrapListenerBlock_1tz5yf(
  int port,
  ffi.Pointer<objc.DOBJC_Context> context,
);

@ffi.Native<
  ffi.Pointer<objc.ObjCBlockImpl> Function(
    ffi.Int64,
    ffi.Pointer<objc.DOBJC_Context>,
  )
>(isLeaf: true)
external ffi.Pointer<objc.ObjCBlockImpl> _x224me_wrapListenerBlock_fjrv01(
  int port,
  ffi.Pointer<objc.DOBJC_Context> context,
);

@ffi.Native<
  ffi.Pointer<objc.ObjCBlockImpl> Function(
    ffi.Int64,
    ffi.Pointer<objc.DOBJC_Context>,
  )
>(isLeaf: true)
external ffi.Pointer<objc.ObjCBlockImpl> _x224me_wrapListenerBlock_xtuoz7(
  int port,
  ffi.Pointer<objc.DOBJC_Context> context,
);

/// WARNING: AVPictureInPictureController is a stub. To generate bindings for this class, include
/// AVPictureInPictureController in your config's objc-interfaces list.
///
/// AVPictureInPictureController
extension type AVPictureInPictureController._(objc.ObjCObject object$)
    implements objc.ObjCObject {
  /// Constructs a [AVPictureInPictureController] that points to the same underlying object as [other].
  AVPictureInPictureController.as(objc.ObjCObject other) : object$ = other {}

  /// Constructs a [AVPictureInPictureController] that wraps the given raw object pointer.
  AVPictureInPictureController.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {}
}

/// A platform view implementation that wraps AVPlayer for video playback.
/// Handles player initialization, lifecycle, and event reporting to Flutter.
extension type BetterPlayer._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [BetterPlayer] that points to the same underlying object as [other].
  BetterPlayer.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [BetterPlayer] that wraps the given raw object pointer.
  BetterPlayer.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [BetterPlayer].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_19nvye5(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_BetterPlayer,
        );

  /// alloc
  static BetterPlayer alloc() {
    final $ret = _objc_msgSend_151sglz(_class_BetterPlayer, _sel_alloc);
    return BetterPlayer.fromPointer($ret, retain: false, release: true);
  }

  /// allocWithZone:
  static BetterPlayer allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1cwp428(
      _class_BetterPlayer,
      _sel_allocWithZone_,
      zone,
    );
    return BetterPlayer.fromPointer($ret, retain: false, release: true);
  }

  /// new
  static BetterPlayer new$() {
    final $ret = _objc_msgSend_151sglz(_class_BetterPlayer, _sel_new);
    return BetterPlayer.fromPointer($ret, retain: false, release: true);
  }

  /// Returns a new instance of BetterPlayer constructed with the default `new` method.
  BetterPlayer() : this.as(new$().object$);
}

extension BetterPlayer$Methods on BetterPlayer {
  /// The sink for emitting events to Flutter.
  BetterPlayerCallback? get callback {
    final _$$ref = object$.ref;
    final $ret = _objc_msgSend_151sglz(_$$ref.pointer, _sel_callback);
    return $ret.address == 0
        ? null
        : BetterPlayerCallback.fromPointer($ret, retain: true, release: true);
  }

  /// Disposes the player and cleans up resources.
  void dispose() {
    final _$$ref = object$.ref;
    _objc_msgSend_1pl9qdv(_$$ref.pointer, _sel_dispose);
  }

  /// init
  BetterPlayer init() {
    final _$$ref = object$.ref;
    objc.checkOsVersionInternal(
      'BetterPlayer.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      _$$ref.retainAndReturnPointer(),
      _sel_init,
    );
    return BetterPlayer.fromPointer($ret, retain: false, release: true);
  }

  /// observeValueForKeyPath:ofObject:change:context:
  void observeValueForKeyPath(
    objc.NSString? keyPath, {
    objc.ObjCObject? ofObject,
    objc.NSDictionary? change,
    required ffi.Pointer<ffi.Void> context,
  }) {
    final _$$ref = object$.ref;
    final _$$ref$1 = keyPath?.ref;
    final _$$ref$2 = ofObject?.ref;
    final _$$ref$3 = change?.ref;
    _objc_msgSend_1pl4k3n(
      _$$ref.pointer,
      _sel_observeValueForKeyPath_ofObject_change_context_,
      _$$ref$1?.pointer ?? ffi.nullptr,
      _$$ref$2?.pointer ?? ffi.nullptr,
      _$$ref$3?.pointer ?? ffi.nullptr,
      context,
    );
  }

  /// Pauses playback.
  void pause() {
    final _$$ref = object$.ref;
    _objc_msgSend_1pl9qdv(_$$ref.pointer, _sel_pause);
  }

  /// pictureInPictureController:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:
  void pictureInPictureController(
    AVPictureInPictureController pictureInPictureController, {
    required objc.ObjCBlock<ffi.Void Function(ffi.Bool)>
    restoreUserInterfaceForPictureInPictureStopWithCompletionHandler,
  }) {
    final _$$ref = object$.ref;
    final _$$ref$1 = pictureInPictureController.ref;
    final _$$ref$2 =
        restoreUserInterfaceForPictureInPictureStopWithCompletionHandler.ref;
    _objc_msgSend_o762yo(
      _$$ref.pointer,
      _sel_pictureInPictureController_restoreUserInterfaceForPictureInPictureStopWithCompletionHandler_,
      _$$ref$1.pointer,
      _$$ref$2.pointer,
    );
  }

  /// pictureInPictureControllerDidStartPictureInPicture:
  void pictureInPictureControllerDidStartPictureInPicture(
    AVPictureInPictureController pictureInPictureController,
  ) {
    final _$$ref = object$.ref;
    final _$$ref$1 = pictureInPictureController.ref;
    _objc_msgSend_xtuoz7(
      _$$ref.pointer,
      _sel_pictureInPictureControllerDidStartPictureInPicture_,
      _$$ref$1.pointer,
    );
  }

  /// pictureInPictureControllerDidStopPictureInPicture:
  void pictureInPictureControllerDidStopPictureInPicture(
    AVPictureInPictureController pictureInPictureController,
  ) {
    final _$$ref = object$.ref;
    final _$$ref$1 = pictureInPictureController.ref;
    _objc_msgSend_xtuoz7(
      _$$ref.pointer,
      _sel_pictureInPictureControllerDidStopPictureInPicture_,
      _$$ref$1.pointer,
    );
  }

  /// Starts playback.
  void play() {
    final _$$ref = object$.ref;
    _objc_msgSend_1pl9qdv(_$$ref.pointer, _sel_play);
  }

  /// Seeks to the specified position in milliseconds.
  /// \param location The position to seek to.
  void seekTo(int location) {
    final _$$ref = object$.ref;
    _objc_msgSend_4sp4xj(_$$ref.pointer, _sel_seekTo_, location);
  }

  /// Sets the audio track by name and index.
  /// \param name The name of the track.
  ///
  /// \param index The index of the track.
  void setAudioTrackWithName(objc.NSString name, {required int index}) {
    final _$$ref = object$.ref;
    final _$$ref$1 = name.ref;
    _objc_msgSend_1nvl641(
      _$$ref.pointer,
      _sel_setAudioTrackWithName_index_,
      _$$ref$1.pointer,
      index,
    );
  }

  /// The sink for emitting events to Flutter.
  set callback(BetterPlayerCallback? value) {
    final _$$ref = object$.ref;
    final _$$ref$1 = value?.ref;
    _objc_msgSend_xtuoz7(
      _$$ref.pointer,
      _sel_setCallback_,
      _$$ref$1?.pointer ?? ffi.nullptr,
    );
  }

  /// Sets whether the audio should mix with others.
  /// \param mixWithOthers Whether to mix audio.
  void setMixWithOthers(bool mixWithOthers) {
    final _$$ref = object$.ref;
    _objc_msgSend_1s56lr9(
      _$$ref.pointer,
      _sel_setMixWithOthers_,
      mixWithOthers,
    );
  }

  /// Sets the playback speed.
  /// \param speed The playback speed.
  ///
  /// \param result The Flutter result to report success or failure.
  void setSpeed(
    double speed, {
    required objc.ObjCBlock<
      ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl>?)
    >
    result,
  }) {
    final _$$ref = object$.ref;
    final _$$ref$1 = result.ref;
    _objc_msgSend_16dy26p(
      _$$ref.pointer,
      _sel_setSpeed_result_,
      speed,
      _$$ref$1.pointer,
    );
  }

  /// Sets track parameters like bitrate and resolution.
  void setTrackParametersWithWidth(
    int width, {
    required int height,
    required int bitrate,
  }) {
    final _$$ref = object$.ref;
    _objc_msgSend_4y51qf(
      _$$ref.pointer,
      _sel_setTrackParametersWithWidth_height_bitrate_,
      width,
      height,
      bitrate,
    );
  }

  /// Sets the player volume.
  /// \param volume The volume level (0.0 to 1.0).
  void setVolume(double volume) {
    final _$$ref = object$.ref;
    _objc_msgSend_hwm8nu(_$$ref.pointer, _sel_setVolume_, volume);
  }

  /// Returns the view to be displayed in Flutter.
  UIView view() {
    final _$$ref = object$.ref;
    final $ret = _objc_msgSend_151sglz(_$$ref.pointer, _sel_view);
    return UIView.fromPointer($ret, retain: true, release: true);
  }
}

/// BetterPlayerApi
extension type BetterPlayerApi._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [BetterPlayerApi] that points to the same underlying object as [other].
  BetterPlayerApi.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [BetterPlayerApi] that wraps the given raw object pointer.
  BetterPlayerApi.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [BetterPlayerApi].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_19nvye5(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_BetterPlayerApi,
        );

  /// alloc
  static BetterPlayerApi alloc() {
    final $ret = _objc_msgSend_151sglz(_class_BetterPlayerApi, _sel_alloc);
    return BetterPlayerApi.fromPointer($ret, retain: false, release: true);
  }

  /// allocWithZone:
  static BetterPlayerApi allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1cwp428(
      _class_BetterPlayerApi,
      _sel_allocWithZone_,
      zone,
    );
    return BetterPlayerApi.fromPointer($ret, retain: false, release: true);
  }

  /// createPlayerWithCallback:
  static int createPlayerWithCallback(BetterPlayerCallback callback) {
    final _$$ref = callback.ref;
    return _objc_msgSend_1oj5o8z(
      _class_BetterPlayerApi,
      _sel_createPlayerWithCallback_,
      _$$ref.pointer,
    );
  }

  /// new
  static BetterPlayerApi new$() {
    final $ret = _objc_msgSend_151sglz(_class_BetterPlayerApi, _sel_new);
    return BetterPlayerApi.fromPointer($ret, retain: false, release: true);
  }

  /// nextId
  static int getNextId() {
    return _objc_msgSend_pysgoz(_class_BetterPlayerApi, _sel_nextId);
  }

  /// players
  static objc.NSDictionary getPlayers() {
    final $ret = _objc_msgSend_151sglz(_class_BetterPlayerApi, _sel_players);
    return objc.NSDictionary.fromPointer($ret, retain: true, release: true);
  }

  /// setNextId:
  static void setNextId(int value) {
    _objc_msgSend_17gvxvj(_class_BetterPlayerApi, _sel_setNextId_, value);
  }

  /// setPlayers:
  static void setPlayers(objc.NSDictionary value) {
    final _$$ref = value.ref;
    _objc_msgSend_xtuoz7(
      _class_BetterPlayerApi,
      _sel_setPlayers_,
      _$$ref.pointer,
    );
  }

  /// Returns a new instance of BetterPlayerApi constructed with the default `new` method.
  BetterPlayerApi() : this.as(new$().object$);
}

extension BetterPlayerApi$Methods on BetterPlayerApi {
  /// init
  BetterPlayerApi init() {
    final _$$ref$1 = object$.ref;
    objc.checkOsVersionInternal(
      'BetterPlayerApi.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      _$$ref$1.retainAndReturnPointer(),
      _sel_init,
    );
    return BetterPlayerApi.fromPointer($ret, retain: false, release: true);
  }
}

/// BetterPlayerCallback
extension type BetterPlayerCallback._(objc.ObjCProtocol object$)
    implements objc.ObjCProtocol {
  /// Constructs a [BetterPlayerCallback] that points to the same underlying object as [other].
  BetterPlayerCallback.as(objc.ObjCObject other) : object$ = other;

  /// Constructs a [BetterPlayerCallback] that wraps the given raw object pointer.
  BetterPlayerCallback.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCProtocol(other, retain: retain, release: release);

  /// Returns whether [obj] is an instance of [BetterPlayerCallback].
  static bool conformsTo(objc.ObjCObject obj) {
    return _objc_msgSend_e3qsqz(
      obj.ref.pointer,
      _sel_conformsToProtocol_,
      _protocol_BetterPlayerCallback,
    );
  }
}

extension BetterPlayerCallback$Methods on BetterPlayerCallback {
  /// onError:errorMessage:errorDetails:
  void onError(
    objc.NSString errorCode, {
    required objc.NSString errorMessage,
    required objc.NSString errorDetails,
  }) {
    final _$$ref = object$.ref;
    final _$$ref$1 = errorCode.ref;
    final _$$ref$2 = errorMessage.ref;
    final _$$ref$3 = errorDetails.ref;
    _objc_msgSend_r8gdi7(
      _$$ref.pointer,
      _sel_onError_errorMessage_errorDetails_,
      _$$ref$1.pointer,
      _$$ref$2.pointer,
      _$$ref$3.pointer,
    );
  }

  /// onEvent:parameters:
  void onEvent(objc.NSString event, {required objc.NSString parameters}) {
    final _$$ref = object$.ref;
    final _$$ref$1 = event.ref;
    final _$$ref$2 = parameters.ref;
    _objc_msgSend_pfv6jd(
      _$$ref.pointer,
      _sel_onEvent_parameters_,
      _$$ref$1.pointer,
      _$$ref$2.pointer,
    );
  }
}

interface class BetterPlayerCallback$Builder {
  /// Returns the [objc.Protocol] object for this protocol.
  static objc.Protocol get $protocol =>
      objc.Protocol.fromPointer(_protocol_BetterPlayerCallback.cast());

  /// Builds an object that implements the BetterPlayerCallback protocol. To implement
  /// multiple protocols, use [addToBuilder] or [objc.ObjCProtocolBuilder] directly.
  ///
  /// If `$keepIsolateAlive` is true, this protocol will keep this isolate
  /// alive until it is garbage collected by both Dart and ObjC.
  static BetterPlayerCallback implement({
    required void Function(objc.NSString, objc.NSString, objc.NSString)
    onError_errorMessage_errorDetails_,
    required void Function(objc.NSString, objc.NSString) onEvent_parameters_,
    bool $keepIsolateAlive = true,
  }) {
    final builder = objc.ObjCProtocolBuilder(debugName: 'BetterPlayerCallback');
    BetterPlayerCallback$Builder.onError_errorMessage_errorDetails_.implement(
      builder,
      onError_errorMessage_errorDetails_,
    );
    BetterPlayerCallback$Builder.onEvent_parameters_.implement(
      builder,
      onEvent_parameters_,
    );
    builder.addProtocol($protocol);
    return BetterPlayerCallback.as(
      builder.build(keepIsolateAlive: $keepIsolateAlive),
    );
  }

  /// Adds the implementation of the BetterPlayerCallback protocol to an existing
  /// [objc.ObjCProtocolBuilder].
  ///
  /// Note: You cannot call this method after you have called `builder.build`.
  static void addToBuilder(
    objc.ObjCProtocolBuilder builder, {
    required void Function(objc.NSString, objc.NSString, objc.NSString)
    onError_errorMessage_errorDetails_,
    required void Function(objc.NSString, objc.NSString) onEvent_parameters_,
    bool $keepIsolateAlive = true,
  }) {
    BetterPlayerCallback$Builder.onError_errorMessage_errorDetails_.implement(
      builder,
      onError_errorMessage_errorDetails_,
    );
    BetterPlayerCallback$Builder.onEvent_parameters_.implement(
      builder,
      onEvent_parameters_,
    );
    builder.addProtocol($protocol);
  }

  /// Builds an object that implements the BetterPlayerCallback protocol. To implement
  /// multiple protocols, use [addToBuilder] or [objc.ObjCProtocolBuilder] directly. All
  /// methods that can be implemented as listeners will be.
  ///
  /// If `$keepIsolateAlive` is true, this protocol will keep this isolate
  /// alive until it is garbage collected by both Dart and ObjC.
  static BetterPlayerCallback implementAsListener({
    required void Function(objc.NSString, objc.NSString, objc.NSString)
    onError_errorMessage_errorDetails_,
    required void Function(objc.NSString, objc.NSString) onEvent_parameters_,
    bool $keepIsolateAlive = true,
  }) {
    final builder = objc.ObjCProtocolBuilder(debugName: 'BetterPlayerCallback');
    BetterPlayerCallback$Builder.onError_errorMessage_errorDetails_
        .implementAsListener(builder, onError_errorMessage_errorDetails_);
    BetterPlayerCallback$Builder.onEvent_parameters_.implementAsListener(
      builder,
      onEvent_parameters_,
    );
    builder.addProtocol($protocol);
    return BetterPlayerCallback.as(
      builder.build(keepIsolateAlive: $keepIsolateAlive),
    );
  }

  /// Adds the implementation of the BetterPlayerCallback protocol to an existing
  /// [objc.ObjCProtocolBuilder]. All methods that can be implemented as listeners will
  /// be.
  ///
  /// Note: You cannot call this method after you have called `builder.build`.
  static void addToBuilderAsListener(
    objc.ObjCProtocolBuilder builder, {
    required void Function(objc.NSString, objc.NSString, objc.NSString)
    onError_errorMessage_errorDetails_,
    required void Function(objc.NSString, objc.NSString) onEvent_parameters_,
    bool $keepIsolateAlive = true,
  }) {
    BetterPlayerCallback$Builder.onError_errorMessage_errorDetails_
        .implementAsListener(builder, onError_errorMessage_errorDetails_);
    BetterPlayerCallback$Builder.onEvent_parameters_.implementAsListener(
      builder,
      onEvent_parameters_,
    );
    builder.addProtocol($protocol);
  }

  /// Builds an object that implements the BetterPlayerCallback protocol. To implement
  /// multiple protocols, use [addToBuilder] or [objc.ObjCProtocolBuilder] directly. All
  /// methods that can be implemented as blocking listeners will be.
  ///
  /// If `$keepIsolateAlive` is true, this protocol will keep this isolate
  /// alive until it is garbage collected by both Dart and ObjC.
  static BetterPlayerCallback implementAsBlocking({
    required void Function(objc.NSString, objc.NSString, objc.NSString)
    onError_errorMessage_errorDetails_,
    required void Function(objc.NSString, objc.NSString) onEvent_parameters_,
    bool $keepIsolateAlive = true,
  }) {
    final builder = objc.ObjCProtocolBuilder(debugName: 'BetterPlayerCallback');
    BetterPlayerCallback$Builder.onError_errorMessage_errorDetails_
        .implementAsBlocking(builder, onError_errorMessage_errorDetails_);
    BetterPlayerCallback$Builder.onEvent_parameters_.implementAsBlocking(
      builder,
      onEvent_parameters_,
    );
    builder.addProtocol($protocol);
    return BetterPlayerCallback.as(
      builder.build(keepIsolateAlive: $keepIsolateAlive),
    );
  }

  /// Adds the implementation of the BetterPlayerCallback protocol to an existing
  /// [objc.ObjCProtocolBuilder]. All methods that can be implemented as blocking
  /// listeners will be.
  ///
  /// Note: You cannot call this method after you have called `builder.build`.
  static void addToBuilderAsBlocking(
    objc.ObjCProtocolBuilder builder, {
    required void Function(objc.NSString, objc.NSString, objc.NSString)
    onError_errorMessage_errorDetails_,
    required void Function(objc.NSString, objc.NSString) onEvent_parameters_,
    bool $keepIsolateAlive = true,
  }) {
    BetterPlayerCallback$Builder.onError_errorMessage_errorDetails_
        .implementAsBlocking(builder, onError_errorMessage_errorDetails_);
    BetterPlayerCallback$Builder.onEvent_parameters_.implementAsBlocking(
      builder,
      onEvent_parameters_,
    );
    builder.addProtocol($protocol);
  }

  /// onError:errorMessage:errorDetails:
  static final onError_errorMessage_errorDetails_ =
      objc.ObjCProtocolListenableMethod<
        void Function(objc.NSString, objc.NSString, objc.NSString)
      >(
        _protocol_BetterPlayerCallback,
        _sel_onError_errorMessage_errorDetails_,
        ffi.Native.addressOf<
              ffi.NativeFunction<
                ffi.Void Function(
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                )
              >
            >(_x224me_protocolTrampoline_1tz5yf)
            .cast(),
        objc.getProtocolMethodSignature(
          _protocol_BetterPlayerCallback,
          _sel_onError_errorMessage_errorDetails_,
          isRequired: true,
          isInstanceMethod: true,
        ),
        (void Function(objc.NSString, objc.NSString, objc.NSString) func) =>
            ObjCBlock_ffiVoid_ffiVoid_NSString_NSString_NSString.fromFunction(
              (
                ffi.Pointer<ffi.Void> _,
                objc.NSString arg1,
                objc.NSString arg2,
                objc.NSString arg3,
              ) => func(arg1, arg2, arg3),
            ),
        (void Function(objc.NSString, objc.NSString, objc.NSString) func) =>
            ObjCBlock_ffiVoid_ffiVoid_NSString_NSString_NSString.listener(
              (
                ffi.Pointer<ffi.Void> _,
                objc.NSString arg1,
                objc.NSString arg2,
                objc.NSString arg3,
              ) => func(arg1, arg2, arg3),
            ),
        (void Function(objc.NSString, objc.NSString, objc.NSString) func) =>
            ObjCBlock_ffiVoid_ffiVoid_NSString_NSString_NSString.blocking(
              (
                ffi.Pointer<ffi.Void> _,
                objc.NSString arg1,
                objc.NSString arg2,
                objc.NSString arg3,
              ) => func(arg1, arg2, arg3),
            ),
      );

  /// onEvent:parameters:
  static final onEvent_parameters_ =
      objc.ObjCProtocolListenableMethod<
        void Function(objc.NSString, objc.NSString)
      >(
        _protocol_BetterPlayerCallback,
        _sel_onEvent_parameters_,
        ffi.Native.addressOf<
              ffi.NativeFunction<
                ffi.Void Function(
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                )
              >
            >(_x224me_protocolTrampoline_fjrv01)
            .cast(),
        objc.getProtocolMethodSignature(
          _protocol_BetterPlayerCallback,
          _sel_onEvent_parameters_,
          isRequired: true,
          isInstanceMethod: true,
        ),
        (void Function(objc.NSString, objc.NSString) func) =>
            ObjCBlock_ffiVoid_ffiVoid_NSString_NSString.fromFunction(
              (
                ffi.Pointer<ffi.Void> _,
                objc.NSString arg1,
                objc.NSString arg2,
              ) => func(arg1, arg2),
            ),
        (void Function(objc.NSString, objc.NSString) func) =>
            ObjCBlock_ffiVoid_ffiVoid_NSString_NSString.listener(
              (
                ffi.Pointer<ffi.Void> _,
                objc.NSString arg1,
                objc.NSString arg2,
              ) => func(arg1, arg2),
            ),
        (void Function(objc.NSString, objc.NSString) func) =>
            ObjCBlock_ffiVoid_ffiVoid_NSString_NSString.blocking(
              (
                ffi.Pointer<ffi.Void> _,
                objc.NSString arg1,
                objc.NSString arg2,
              ) => func(arg1, arg2),
            ),
      );
}

/// Construction methods for `objc.ObjCBlock<ffi.Void Function(ffi.Bool)>`.
abstract final class ObjCBlock_ffiVoid_bool {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<ffi.Void Function(ffi.Bool)> fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) => objc.ObjCBlock<ffi.Void Function(ffi.Bool)>(
    pointer,
    retain: retain,
    release: release,
  );

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<ffi.Void Function(ffi.Bool)> fromFunctionPointer(
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Bool arg0)>> ptr,
  ) => objc.ObjCBlock<ffi.Void Function(ffi.Bool)>(
    objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
    retain: false,
    release: true,
  );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<ffi.Void Function(ffi.Bool)> fromFunction(
    void Function(bool) fn, {
    bool keepIsolateAlive = true,
  }) => objc.ObjCBlock<ffi.Void Function(ffi.Bool)>(
    objc.newClosureBlock(_closureCallable, (bool arg0) {
      return fn(arg0);
    }, keepIsolateAlive),
    retain: false,
    release: true,
  );

  /// Creates a listener block from a Dart function.
  ///
  /// This block can be invoked from any thread, but only supports void
  /// functions, and is not run synchronously. Async functions (ie returning
  /// Future<void>) are not supported.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<ffi.Void Function(ffi.Bool)> listener(
    void Function(bool) fn, {
    bool keepIsolateAlive = true,
  }) {
    return objc.ObjCBlock<ffi.Void Function(ffi.Bool)>(
      objc.newBlockPort(_x224me_wrapListenerBlock_1s56lr9, (
        ffi.Pointer<objc.ObjCObjectImpl> rawArgs,
      ) {
        final args = _BlockArgs_k4je64.fromPointer(
          rawArgs,
          retain: false,
          release: false,
        );

        fn(args.arg0);
      }, keepIsolateAlive),
      retain: false,
      release: true,
    );
  }

  /// Creates a blocking block from a Dart function.
  ///
  /// This callback can be invoked from any native thread, and will block the
  /// caller until the callback is handled by the Dart isolate that created
  /// the block. Async functions (ie returning Future<void>) are not supported.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC. If the owner isolate
  /// has shut down, and the block is invoked by native code, it may block
  /// indefinitely, or have other undefined behavior.
  static objc.ObjCBlock<ffi.Void Function(ffi.Bool)> blocking(
    void Function(bool) fn, {
    bool keepIsolateAlive = true,
  }) {
    return objc.ObjCBlock<ffi.Void Function(ffi.Bool)>(
      objc.newBlockingBlockPort(_x224me_wrapBlockingBlock_1s56lr9, (
        ffi.Pointer<objc.ObjCObjectImpl> rawArgs,
      ) {
        final args = _BlockArgs_k4je64.fromPointer(
          rawArgs,
          retain: false,
          release: false,
        );

        fn(args.arg0);
      }, keepIsolateAlive),
      retain: false,
      release: true,
    );
  }

  static void _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    bool arg0,
  ) => block.ref.target
      .cast<ffi.NativeFunction<ffi.Void Function(ffi.Bool arg0)>>()
      .asFunction<void Function(bool)>()(arg0);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Void Function(ffi.Pointer<objc.ObjCBlockImpl>, ffi.Bool)
          >(_fnPtrTrampoline)
          .cast();
  static void _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    bool arg0,
  ) => (objc.getBlockClosure(block) as void Function(bool))(arg0);
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Void Function(ffi.Pointer<objc.ObjCBlockImpl>, ffi.Bool)
          >(_closureTrampoline)
          .cast();
}

/// Call operator for `objc.ObjCBlock<ffi.Void Function(ffi.Bool)>`.
extension ObjCBlock_ffiVoid_bool$CallExtension
    on objc.ObjCBlock<ffi.Void Function(ffi.Bool)> {
  void call(bool arg0) {
    return ref.pointer.ref.invoke
        .cast<
          ffi.NativeFunction<
            ffi.Void Function(
              ffi.Pointer<objc.ObjCBlockImpl> block,
              ffi.Bool arg0,
            )
          >
        >()
        .asFunction<void Function(ffi.Pointer<objc.ObjCBlockImpl>, bool)>()(
      ref.pointer,
      arg0,
    );
  }
}

/// Construction methods for `objc.ObjCBlock<ffi.Void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString)>`.
abstract final class ObjCBlock_ffiVoid_ffiVoid_NSString_NSString {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<
    ffi.Void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString)
  >
  fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) =>
      objc.ObjCBlock<
        ffi.Void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString)
      >(pointer, retain: retain, release: release);

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<
    ffi.Void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString)
  >
  fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> arg0,
          ffi.Pointer<objc.ObjCObjectImpl> arg1,
          ffi.Pointer<objc.ObjCObjectImpl> arg2,
        )
      >
    >
    ptr,
  ) =>
      objc.ObjCBlock<
        ffi.Void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString)
      >(
        objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
        retain: false,
        release: true,
      );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<
    ffi.Void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString)
  >
  fromFunction(
    void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString) fn, {
    bool keepIsolateAlive = true,
  }) =>
      objc.ObjCBlock<
        ffi.Void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString)
      >(
        objc.newClosureBlock(_closureCallable, (
          ffi.Pointer<ffi.Void> arg0,
          ffi.Pointer<objc.ObjCObjectImpl> arg1,
          ffi.Pointer<objc.ObjCObjectImpl> arg2,
        ) {
          return fn(
            arg0,
            objc.NSString.fromPointer(arg1, retain: true, release: true),
            objc.NSString.fromPointer(arg2, retain: true, release: true),
          );
        }, keepIsolateAlive),
        retain: false,
        release: true,
      );

  /// Creates a listener block from a Dart function.
  ///
  /// This block can be invoked from any thread, but only supports void
  /// functions, and is not run synchronously. Async functions (ie returning
  /// Future<void>) are not supported.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<
    ffi.Void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString)
  >
  listener(
    void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString) fn, {
    bool keepIsolateAlive = true,
  }) {
    return objc.ObjCBlock<
      ffi.Void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString)
    >(
      objc.newBlockPort(_x224me_wrapListenerBlock_fjrv01, (
        ffi.Pointer<objc.ObjCObjectImpl> rawArgs,
      ) {
        final args = _BlockArgs_1ptzs7z.fromPointer(
          rawArgs,
          retain: false,
          release: false,
        );

        fn(args.arg0, args.arg1, args.arg2);
      }, keepIsolateAlive),
      retain: false,
      release: true,
    );
  }

  /// Creates a blocking block from a Dart function.
  ///
  /// This callback can be invoked from any native thread, and will block the
  /// caller until the callback is handled by the Dart isolate that created
  /// the block. Async functions (ie returning Future<void>) are not supported.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC. If the owner isolate
  /// has shut down, and the block is invoked by native code, it may block
  /// indefinitely, or have other undefined behavior.
  static objc.ObjCBlock<
    ffi.Void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString)
  >
  blocking(
    void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString) fn, {
    bool keepIsolateAlive = true,
  }) {
    return objc.ObjCBlock<
      ffi.Void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString)
    >(
      objc.newBlockingBlockPort(_x224me_wrapBlockingBlock_fjrv01, (
        ffi.Pointer<objc.ObjCObjectImpl> rawArgs,
      ) {
        final args = _BlockArgs_1ptzs7z.fromPointer(
          rawArgs,
          retain: false,
          release: false,
        );

        fn(args.arg0, args.arg1, args.arg2);
      }, keepIsolateAlive),
      retain: false,
      release: true,
    );
  }

  static void _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
    ffi.Pointer<objc.ObjCObjectImpl> arg1,
    ffi.Pointer<objc.ObjCObjectImpl> arg2,
  ) => block.ref.target
      .cast<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void> arg0,
            ffi.Pointer<objc.ObjCObjectImpl> arg1,
            ffi.Pointer<objc.ObjCObjectImpl> arg2,
          )
        >
      >()
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >()(arg0, arg1, arg2);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Void Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_fnPtrTrampoline)
          .cast();
  static void _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
    ffi.Pointer<objc.ObjCObjectImpl> arg1,
    ffi.Pointer<objc.ObjCObjectImpl> arg2,
  ) =>
      (objc.getBlockClosure(block)
          as void Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<objc.ObjCObjectImpl>,
            ffi.Pointer<objc.ObjCObjectImpl>,
          ))(arg0, arg1, arg2);
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Void Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_closureTrampoline)
          .cast();
}

/// Call operator for `objc.ObjCBlock<ffi.Void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString)>`.
extension ObjCBlock_ffiVoid_ffiVoid_NSString_NSString$CallExtension
    on
        objc.ObjCBlock<
          ffi.Void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString)
        > {
  void call(
    ffi.Pointer<ffi.Void> arg0,
    objc.NSString arg1,
    objc.NSString arg2,
  ) {
    final _$$ref = arg1.ref;
    final _$$ref$1 = arg2.ref;
    return ref.pointer.ref.invoke
        .cast<
          ffi.NativeFunction<
            ffi.Void Function(
              ffi.Pointer<objc.ObjCBlockImpl> block,
              ffi.Pointer<ffi.Void> arg0,
              ffi.Pointer<objc.ObjCObjectImpl> arg1,
              ffi.Pointer<objc.ObjCObjectImpl> arg2,
            )
          >
        >()
        .asFunction<
          void Function(
            ffi.Pointer<objc.ObjCBlockImpl>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<objc.ObjCObjectImpl>,
            ffi.Pointer<objc.ObjCObjectImpl>,
          )
        >()(ref.pointer, arg0, _$$ref.pointer, _$$ref$1.pointer);
  }
}

/// Construction methods for `objc.ObjCBlock<ffi.Void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString, objc.NSString)>`.
abstract final class ObjCBlock_ffiVoid_ffiVoid_NSString_NSString_NSString {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<
    ffi.Void Function(
      ffi.Pointer<ffi.Void>,
      objc.NSString,
      objc.NSString,
      objc.NSString,
    )
  >
  fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) =>
      objc.ObjCBlock<
        ffi.Void Function(
          ffi.Pointer<ffi.Void>,
          objc.NSString,
          objc.NSString,
          objc.NSString,
        )
      >(pointer, retain: retain, release: release);

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<
    ffi.Void Function(
      ffi.Pointer<ffi.Void>,
      objc.NSString,
      objc.NSString,
      objc.NSString,
    )
  >
  fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Void> arg0,
          ffi.Pointer<objc.ObjCObjectImpl> arg1,
          ffi.Pointer<objc.ObjCObjectImpl> arg2,
          ffi.Pointer<objc.ObjCObjectImpl> arg3,
        )
      >
    >
    ptr,
  ) =>
      objc.ObjCBlock<
        ffi.Void Function(
          ffi.Pointer<ffi.Void>,
          objc.NSString,
          objc.NSString,
          objc.NSString,
        )
      >(
        objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
        retain: false,
        release: true,
      );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<
    ffi.Void Function(
      ffi.Pointer<ffi.Void>,
      objc.NSString,
      objc.NSString,
      objc.NSString,
    )
  >
  fromFunction(
    void Function(
      ffi.Pointer<ffi.Void>,
      objc.NSString,
      objc.NSString,
      objc.NSString,
    )
    fn, {
    bool keepIsolateAlive = true,
  }) =>
      objc.ObjCBlock<
        ffi.Void Function(
          ffi.Pointer<ffi.Void>,
          objc.NSString,
          objc.NSString,
          objc.NSString,
        )
      >(
        objc.newClosureBlock(_closureCallable, (
          ffi.Pointer<ffi.Void> arg0,
          ffi.Pointer<objc.ObjCObjectImpl> arg1,
          ffi.Pointer<objc.ObjCObjectImpl> arg2,
          ffi.Pointer<objc.ObjCObjectImpl> arg3,
        ) {
          return fn(
            arg0,
            objc.NSString.fromPointer(arg1, retain: true, release: true),
            objc.NSString.fromPointer(arg2, retain: true, release: true),
            objc.NSString.fromPointer(arg3, retain: true, release: true),
          );
        }, keepIsolateAlive),
        retain: false,
        release: true,
      );

  /// Creates a listener block from a Dart function.
  ///
  /// This block can be invoked from any thread, but only supports void
  /// functions, and is not run synchronously. Async functions (ie returning
  /// Future<void>) are not supported.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<
    ffi.Void Function(
      ffi.Pointer<ffi.Void>,
      objc.NSString,
      objc.NSString,
      objc.NSString,
    )
  >
  listener(
    void Function(
      ffi.Pointer<ffi.Void>,
      objc.NSString,
      objc.NSString,
      objc.NSString,
    )
    fn, {
    bool keepIsolateAlive = true,
  }) {
    return objc.ObjCBlock<
      ffi.Void Function(
        ffi.Pointer<ffi.Void>,
        objc.NSString,
        objc.NSString,
        objc.NSString,
      )
    >(
      objc.newBlockPort(_x224me_wrapListenerBlock_1tz5yf, (
        ffi.Pointer<objc.ObjCObjectImpl> rawArgs,
      ) {
        final args = _BlockArgs_1pvysg1.fromPointer(
          rawArgs,
          retain: false,
          release: false,
        );

        fn(args.arg0, args.arg1, args.arg2, args.arg3);
      }, keepIsolateAlive),
      retain: false,
      release: true,
    );
  }

  /// Creates a blocking block from a Dart function.
  ///
  /// This callback can be invoked from any native thread, and will block the
  /// caller until the callback is handled by the Dart isolate that created
  /// the block. Async functions (ie returning Future<void>) are not supported.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC. If the owner isolate
  /// has shut down, and the block is invoked by native code, it may block
  /// indefinitely, or have other undefined behavior.
  static objc.ObjCBlock<
    ffi.Void Function(
      ffi.Pointer<ffi.Void>,
      objc.NSString,
      objc.NSString,
      objc.NSString,
    )
  >
  blocking(
    void Function(
      ffi.Pointer<ffi.Void>,
      objc.NSString,
      objc.NSString,
      objc.NSString,
    )
    fn, {
    bool keepIsolateAlive = true,
  }) {
    return objc.ObjCBlock<
      ffi.Void Function(
        ffi.Pointer<ffi.Void>,
        objc.NSString,
        objc.NSString,
        objc.NSString,
      )
    >(
      objc.newBlockingBlockPort(_x224me_wrapBlockingBlock_1tz5yf, (
        ffi.Pointer<objc.ObjCObjectImpl> rawArgs,
      ) {
        final args = _BlockArgs_1pvysg1.fromPointer(
          rawArgs,
          retain: false,
          release: false,
        );

        fn(args.arg0, args.arg1, args.arg2, args.arg3);
      }, keepIsolateAlive),
      retain: false,
      release: true,
    );
  }

  static void _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
    ffi.Pointer<objc.ObjCObjectImpl> arg1,
    ffi.Pointer<objc.ObjCObjectImpl> arg2,
    ffi.Pointer<objc.ObjCObjectImpl> arg3,
  ) => block.ref.target
      .cast<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void> arg0,
            ffi.Pointer<objc.ObjCObjectImpl> arg1,
            ffi.Pointer<objc.ObjCObjectImpl> arg2,
            ffi.Pointer<objc.ObjCObjectImpl> arg3,
          )
        >
      >()
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >()(arg0, arg1, arg2, arg3);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Void Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_fnPtrTrampoline)
          .cast();
  static void _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
    ffi.Pointer<objc.ObjCObjectImpl> arg1,
    ffi.Pointer<objc.ObjCObjectImpl> arg2,
    ffi.Pointer<objc.ObjCObjectImpl> arg3,
  ) =>
      (objc.getBlockClosure(block)
          as void Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<objc.ObjCObjectImpl>,
            ffi.Pointer<objc.ObjCObjectImpl>,
            ffi.Pointer<objc.ObjCObjectImpl>,
          ))(arg0, arg1, arg2, arg3);
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Void Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_closureTrampoline)
          .cast();
}

/// Call operator for `objc.ObjCBlock<ffi.Void Function(ffi.Pointer<ffi.Void>, objc.NSString, objc.NSString, objc.NSString)>`.
extension ObjCBlock_ffiVoid_ffiVoid_NSString_NSString_NSString$CallExtension
    on
        objc.ObjCBlock<
          ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            objc.NSString,
            objc.NSString,
            objc.NSString,
          )
        > {
  void call(
    ffi.Pointer<ffi.Void> arg0,
    objc.NSString arg1,
    objc.NSString arg2,
    objc.NSString arg3,
  ) {
    final _$$ref = arg1.ref;
    final _$$ref$1 = arg2.ref;
    final _$$ref$2 = arg3.ref;
    return ref.pointer.ref.invoke
        .cast<
          ffi.NativeFunction<
            ffi.Void Function(
              ffi.Pointer<objc.ObjCBlockImpl> block,
              ffi.Pointer<ffi.Void> arg0,
              ffi.Pointer<objc.ObjCObjectImpl> arg1,
              ffi.Pointer<objc.ObjCObjectImpl> arg2,
              ffi.Pointer<objc.ObjCObjectImpl> arg3,
            )
          >
        >()
        .asFunction<
          void Function(
            ffi.Pointer<objc.ObjCBlockImpl>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<objc.ObjCObjectImpl>,
            ffi.Pointer<objc.ObjCObjectImpl>,
            ffi.Pointer<objc.ObjCObjectImpl>,
          )
        >()(
      ref.pointer,
      arg0,
      _$$ref.pointer,
      _$$ref$1.pointer,
      _$$ref$2.pointer,
    );
  }
}

/// Construction methods for `objc.ObjCBlock<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl>?)>`.
abstract final class ObjCBlock_ffiVoid_objcObjCObjectImpl {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl>?)>
  fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) => objc.ObjCBlock<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl>?)>(
    pointer,
    retain: retain,
    release: release,
  );

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl>?)>
  fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl> arg0)
      >
    >
    ptr,
  ) => objc.ObjCBlock<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl>?)>(
    objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
    retain: false,
    release: true,
  );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl>?)>
  fromFunction(
    void Function(objc.ObjCObject?) fn, {
    bool keepIsolateAlive = true,
  }) => objc.ObjCBlock<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl>?)>(
    objc.newClosureBlock(_closureCallable, (
      ffi.Pointer<objc.ObjCObjectImpl> arg0,
    ) {
      return fn(
        arg0.address == 0
            ? null
            : objc.ObjCObject(arg0, retain: true, release: true),
      );
    }, keepIsolateAlive),
    retain: false,
    release: true,
  );

  /// Creates a listener block from a Dart function.
  ///
  /// This block can be invoked from any thread, but only supports void
  /// functions, and is not run synchronously. Async functions (ie returning
  /// Future<void>) are not supported.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl>?)>
  listener(void Function(objc.ObjCObject?) fn, {bool keepIsolateAlive = true}) {
    return objc.ObjCBlock<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl>?)>(
      objc.newBlockPort(_x224me_wrapListenerBlock_xtuoz7, (
        ffi.Pointer<objc.ObjCObjectImpl> rawArgs,
      ) {
        final args = _BlockArgs_1boj2ic.fromPointer(
          rawArgs,
          retain: false,
          release: false,
        );

        fn(args.arg0);
      }, keepIsolateAlive),
      retain: false,
      release: true,
    );
  }

  /// Creates a blocking block from a Dart function.
  ///
  /// This callback can be invoked from any native thread, and will block the
  /// caller until the callback is handled by the Dart isolate that created
  /// the block. Async functions (ie returning Future<void>) are not supported.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC. If the owner isolate
  /// has shut down, and the block is invoked by native code, it may block
  /// indefinitely, or have other undefined behavior.
  static objc.ObjCBlock<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl>?)>
  blocking(void Function(objc.ObjCObject?) fn, {bool keepIsolateAlive = true}) {
    return objc.ObjCBlock<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl>?)>(
      objc.newBlockingBlockPort(_x224me_wrapBlockingBlock_xtuoz7, (
        ffi.Pointer<objc.ObjCObjectImpl> rawArgs,
      ) {
        final args = _BlockArgs_1boj2ic.fromPointer(
          rawArgs,
          retain: false,
          release: false,
        );

        fn(args.arg0);
      }, keepIsolateAlive),
      retain: false,
      release: true,
    );
  }

  static void _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<objc.ObjCObjectImpl> arg0,
  ) => block.ref.target
      .cast<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl> arg0)
        >
      >()
      .asFunction<void Function(ffi.Pointer<objc.ObjCObjectImpl>)>()(arg0);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Void Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_fnPtrTrampoline)
          .cast();
  static void _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<objc.ObjCObjectImpl> arg0,
  ) =>
      (objc.getBlockClosure(block)
          as void Function(ffi.Pointer<objc.ObjCObjectImpl>))(arg0);
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Void Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_closureTrampoline)
          .cast();
}

/// Call operator for `objc.ObjCBlock<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl>?)>`.
extension ObjCBlock_ffiVoid_objcObjCObjectImpl$CallExtension
    on objc.ObjCBlock<ffi.Void Function(ffi.Pointer<objc.ObjCObjectImpl>?)> {
  void call(objc.ObjCObject? arg0) {
    final _$$ref = arg0?.ref;
    return ref.pointer.ref.invoke
        .cast<
          ffi.NativeFunction<
            ffi.Void Function(
              ffi.Pointer<objc.ObjCBlockImpl> block,
              ffi.Pointer<objc.ObjCObjectImpl> arg0,
            )
          >
        >()
        .asFunction<
          void Function(
            ffi.Pointer<objc.ObjCBlockImpl>,
            ffi.Pointer<objc.ObjCObjectImpl>,
          )
        >()(ref.pointer, _$$ref?.pointer ?? ffi.nullptr);
  }
}

/// WARNING: UIView is a stub. To generate bindings for this class, include
/// UIView in your config's objc-interfaces list.
///
/// UIView
extension type UIView._(objc.ObjCObject object$) implements objc.ObjCObject {
  /// Constructs a [UIView] that points to the same underlying object as [other].
  UIView.as(objc.ObjCObject other) : object$ = other {}

  /// Constructs a [UIView] that wraps the given raw object pointer.
  UIView.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {}
}

extension type _BlockArgs_1boj2ic._(objc.ObjCObject object$)
    implements objc.ObjCObject {
  /// Constructs a [_BlockArgs_1boj2ic] that points to the same underlying object as [other].
  _BlockArgs_1boj2ic.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [_BlockArgs_1boj2ic] that wraps the given raw object pointer.
  _BlockArgs_1boj2ic.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [_BlockArgs_1boj2ic].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_19nvye5(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class__BlockArgs_1boj2ic,
        );
}

extension _BlockArgs_1boj2ic$Methods on _BlockArgs_1boj2ic {
  objc.ObjCObject? get arg0 {
    final _$$ref = object$.ref;
    final $ret = _objc_msgSend_151sglz(_$$ref.pointer, _sel_arg0);
    return $ret.address == 0
        ? null
        : objc.ObjCObject($ret, retain: true, release: true);
  }
}

extension type _BlockArgs_1ptzs7z._(objc.ObjCObject object$)
    implements objc.ObjCObject {
  /// Constructs a [_BlockArgs_1ptzs7z] that points to the same underlying object as [other].
  _BlockArgs_1ptzs7z.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [_BlockArgs_1ptzs7z] that wraps the given raw object pointer.
  _BlockArgs_1ptzs7z.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [_BlockArgs_1ptzs7z].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_19nvye5(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class__BlockArgs_1ptzs7z,
        );
}

extension _BlockArgs_1ptzs7z$Methods on _BlockArgs_1ptzs7z {
  ffi.Pointer<ffi.Void> get arg0 {
    final _$$ref = object$.ref;
    return _objc_msgSend_6ex6p5(_$$ref.pointer, _sel_arg0);
  }

  objc.NSString get arg1 {
    final _$$ref = object$.ref;
    final $ret = _objc_msgSend_151sglz(_$$ref.pointer, _sel_arg1);
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  objc.NSString get arg2 {
    final _$$ref = object$.ref;
    final $ret = _objc_msgSend_151sglz(_$$ref.pointer, _sel_arg2);
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }
}

extension type _BlockArgs_1pvysg1._(objc.ObjCObject object$)
    implements objc.ObjCObject {
  /// Constructs a [_BlockArgs_1pvysg1] that points to the same underlying object as [other].
  _BlockArgs_1pvysg1.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [_BlockArgs_1pvysg1] that wraps the given raw object pointer.
  _BlockArgs_1pvysg1.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [_BlockArgs_1pvysg1].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_19nvye5(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class__BlockArgs_1pvysg1,
        );
}

extension _BlockArgs_1pvysg1$Methods on _BlockArgs_1pvysg1 {
  ffi.Pointer<ffi.Void> get arg0 {
    final _$$ref = object$.ref;
    return _objc_msgSend_6ex6p5(_$$ref.pointer, _sel_arg0);
  }

  objc.NSString get arg1 {
    final _$$ref = object$.ref;
    final $ret = _objc_msgSend_151sglz(_$$ref.pointer, _sel_arg1);
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  objc.NSString get arg2 {
    final _$$ref = object$.ref;
    final $ret = _objc_msgSend_151sglz(_$$ref.pointer, _sel_arg2);
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  objc.NSString get arg3 {
    final _$$ref = object$.ref;
    final $ret = _objc_msgSend_151sglz(_$$ref.pointer, _sel_arg3);
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }
}

extension type _BlockArgs_k4je64._(objc.ObjCObject object$)
    implements objc.ObjCObject {
  /// Constructs a [_BlockArgs_k4je64] that points to the same underlying object as [other].
  _BlockArgs_k4je64.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [_BlockArgs_k4je64] that wraps the given raw object pointer.
  _BlockArgs_k4je64.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [_BlockArgs_k4je64].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_19nvye5(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class__BlockArgs_k4je64,
        );
}

extension _BlockArgs_k4je64$Methods on _BlockArgs_k4je64 {
  bool get arg0 {
    final _$$ref = object$.ref;
    return _objc_msgSend_91o635(_$$ref.pointer, _sel_arg0);
  }
}

@ffi.Native<ffi.Pointer<objc.ObjCObjectImpl>>(
  symbol: 'OBJC_CLASS_\$__TtC17better_player_ios12BetterPlayer',
)
external ffi.Pointer<objc.ObjCObjectImpl> _class_BetterPlayer_raw;
final _class_BetterPlayer = objc.getClass(
  "better_player_ios.BetterPlayer",
  () => ffi.Native.addressOf<ffi.Pointer<objc.ObjCObjectImpl>>(
    _class_BetterPlayer_raw,
  ).cast(),
);
@ffi.Native<ffi.Pointer<objc.ObjCObjectImpl>>(
  symbol: 'OBJC_CLASS_\$__TtC17better_player_ios15BetterPlayerApi',
)
external ffi.Pointer<objc.ObjCObjectImpl> _class_BetterPlayerApi_raw;
final _class_BetterPlayerApi = objc.getClass(
  "better_player_ios.BetterPlayerApi",
  () => ffi.Native.addressOf<ffi.Pointer<objc.ObjCObjectImpl>>(
    _class_BetterPlayerApi_raw,
  ).cast(),
);
@ffi.Native<ffi.Pointer<objc.ObjCObjectImpl>>(
  symbol: 'OBJC_CLASS_\$__x224me_BlockArgs_xtuoz7',
)
external ffi.Pointer<objc.ObjCObjectImpl> _class__BlockArgs_1boj2ic_raw;
final _class__BlockArgs_1boj2ic = objc.getClass(
  "_x224me_BlockArgs_xtuoz7",
  () => ffi.Native.addressOf<ffi.Pointer<objc.ObjCObjectImpl>>(
    _class__BlockArgs_1boj2ic_raw,
  ).cast(),
);
@ffi.Native<ffi.Pointer<objc.ObjCObjectImpl>>(
  symbol: 'OBJC_CLASS_\$__x224me_BlockArgs_fjrv01',
)
external ffi.Pointer<objc.ObjCObjectImpl> _class__BlockArgs_1ptzs7z_raw;
final _class__BlockArgs_1ptzs7z = objc.getClass(
  "_x224me_BlockArgs_fjrv01",
  () => ffi.Native.addressOf<ffi.Pointer<objc.ObjCObjectImpl>>(
    _class__BlockArgs_1ptzs7z_raw,
  ).cast(),
);
@ffi.Native<ffi.Pointer<objc.ObjCObjectImpl>>(
  symbol: 'OBJC_CLASS_\$__x224me_BlockArgs_1tz5yf',
)
external ffi.Pointer<objc.ObjCObjectImpl> _class__BlockArgs_1pvysg1_raw;
final _class__BlockArgs_1pvysg1 = objc.getClass(
  "_x224me_BlockArgs_1tz5yf",
  () => ffi.Native.addressOf<ffi.Pointer<objc.ObjCObjectImpl>>(
    _class__BlockArgs_1pvysg1_raw,
  ).cast(),
);
@ffi.Native<ffi.Pointer<objc.ObjCObjectImpl>>(
  symbol: 'OBJC_CLASS_\$__x224me_BlockArgs_1s56lr9',
)
external ffi.Pointer<objc.ObjCObjectImpl> _class__BlockArgs_k4je64_raw;
final _class__BlockArgs_k4je64 = objc.getClass(
  "_x224me_BlockArgs_1s56lr9",
  () => ffi.Native.addressOf<ffi.Pointer<objc.ObjCObjectImpl>>(
    _class__BlockArgs_k4je64_raw,
  ).cast(),
);
final _objc_msgSend_151sglz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_16dy26p = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Double,
          ffi.Pointer<objc.ObjCBlockImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        double,
        ffi.Pointer<objc.ObjCBlockImpl>,
      )
    >();
final _objc_msgSend_17gvxvj = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Int64,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
      )
    >();
final _objc_msgSend_19nvye5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_1cwp428 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.NSZone>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.NSZone>,
      )
    >();
final _objc_msgSend_1nvl641 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Long,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        int,
      )
    >();
final _objc_msgSend_1oj5o8z = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Int64 Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_1pl4k3n = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<ffi.Void>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<ffi.Void>,
      )
    >();
final _objc_msgSend_1pl9qdv = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_1s56lr9 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Bool,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        bool,
      )
    >();
final _objc_msgSend_4sp4xj = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Long,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
      )
    >();
final _objc_msgSend_4y51qf = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Long,
          ffi.Long,
          ffi.Long,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
        int,
        int,
      )
    >();
final _objc_msgSend_6ex6p5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<ffi.Void> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_91o635 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_e3qsqz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCProtocolImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCProtocolImpl>,
      )
    >();
final _objc_msgSend_hwm8nu = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Double,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        double,
      )
    >();
final _objc_msgSend_o762yo = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCBlockImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCBlockImpl>,
      )
    >();
final _objc_msgSend_pfv6jd = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_pysgoz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Int64 Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_r8gdi7 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_xtuoz7 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
@ffi.Native<ffi.Pointer<objc.ObjCProtocolImpl> Function()>(
  symbol: '_x224me_BetterPlayerCallback',
)
external ffi.Pointer<objc.ObjCProtocolImpl>
_protocol_BetterPlayerCallback_raw();
final _protocol_BetterPlayerCallback = objc.getProtocol(
  "better_player_ios.BetterPlayerCallback",
  _protocol_BetterPlayerCallback_raw,
);
late final _sel_alloc = objc.registerName("alloc");
late final _sel_allocWithZone_ = objc.registerName("allocWithZone:");
late final _sel_arg0 = objc.registerName("arg0");
late final _sel_arg1 = objc.registerName("arg1");
late final _sel_arg2 = objc.registerName("arg2");
late final _sel_arg3 = objc.registerName("arg3");
late final _sel_callback = objc.registerName("callback");
late final _sel_conformsToProtocol_ = objc.registerName("conformsToProtocol:");
late final _sel_createPlayerWithCallback_ = objc.registerName(
  "createPlayerWithCallback:",
);
late final _sel_dispose = objc.registerName("dispose");
late final _sel_init = objc.registerName("init");
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
late final _sel_new = objc.registerName("new");
late final _sel_nextId = objc.registerName("nextId");
late final _sel_observeValueForKeyPath_ofObject_change_context_ = objc
    .registerName("observeValueForKeyPath:ofObject:change:context:");
late final _sel_onError_errorMessage_errorDetails_ = objc.registerName(
  "onError:errorMessage:errorDetails:",
);
late final _sel_onEvent_parameters_ = objc.registerName("onEvent:parameters:");
late final _sel_pause = objc.registerName("pause");
late final _sel_pictureInPictureControllerDidStartPictureInPicture_ = objc
    .registerName("pictureInPictureControllerDidStartPictureInPicture:");
late final _sel_pictureInPictureControllerDidStopPictureInPicture_ = objc
    .registerName("pictureInPictureControllerDidStopPictureInPicture:");
late final _sel_pictureInPictureController_restoreUserInterfaceForPictureInPictureStopWithCompletionHandler_ =
    objc.registerName(
      "pictureInPictureController:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:",
    );
late final _sel_play = objc.registerName("play");
late final _sel_players = objc.registerName("players");
late final _sel_seekTo_ = objc.registerName("seekTo:");
late final _sel_setAudioTrackWithName_index_ = objc.registerName(
  "setAudioTrackWithName:index:",
);
late final _sel_setCallback_ = objc.registerName("setCallback:");
late final _sel_setMixWithOthers_ = objc.registerName("setMixWithOthers:");
late final _sel_setNextId_ = objc.registerName("setNextId:");
late final _sel_setPlayers_ = objc.registerName("setPlayers:");
late final _sel_setSpeed_result_ = objc.registerName("setSpeed:result:");
late final _sel_setTrackParametersWithWidth_height_bitrate_ = objc.registerName(
  "setTrackParametersWithWidth:height:bitrate:",
);
late final _sel_setVolume_ = objc.registerName("setVolume:");
late final _sel_view = objc.registerName("view");
typedef instancetype = ffi.Pointer<objc.ObjCObjectImpl>;
typedef Dartinstancetype = objc.ObjCObject;
