name: Quality Gate

on:
  push:

jobs:
  format:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Install LCOV
        run: brew install lcov

      - name: Run tests
        run: flutter test --coverage

      - name: Generate HTML Report
        run: genhtml coverage/lcov.info --output-directory coverage/html

      - name: Upload HTML Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-html
          path: coverage/html

      - name: Add Coverage Summary to Workflow Output
        run: |
          echo "## Coverage Summary" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Coverage |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          lcov --summary coverage/lcov.info | grep -E 'lines|functions|branches' | sed 's/^  //' | awk -F': ' '{print "| " $1 " | " $2 " |"}' >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
