name: Web Tests Debug

on:
  workflow_dispatch:
  push:
    branches:
      - feat/better-player-web-tets

jobs:
  run-web-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get
          cd packages/better_player_web && flutter pub get

      - name: Run Web Tests (flutter run)
        run: |
          cd packages/better_player_web
          # Run flutter directly and let it stream to stdout.
          flutter run -d chrome test/all_tests.dart --release --no-pub
